const express=require('express')
const { default: helmet } = require('helmet')
const cors=require('cors')
const cookieParser=require('cookie-parser')
const app=express()
const connectdb=require("./database")
connectdb()
app.use(cors())
app.use(helmet)
app.use(express.json())
app.use(cookieParser())
app.listen(process.env.PORT, () => {
    console.log(`Server listening at port ${process.env.PORT}`) 
})